### ISSUE TITLE
Library not compatible with Python 3.7.3 (Raspbian Buster)

### ISSUE THREAD

**Issue by koenvervloesem** [t4skforce/epd-library#3]
The library is not compatible with Python 3.7.3 (on Raspbian Buster). This has been fixed upstream: https://github.com/soonuse/epd-library-python/issues/11

Could you pull in this fix and update the pip package?

**Comment by dhalucario** [comment]
I ran into this bug. One error I get is trying to use the epd2in13b library:

```
(venv) pi@pizero:~/workspace/waveshare_imageloader $ epd2in13b
Traceback (most recent call last):
  File "/home/pi/workspace/waveshare_imageloader/venv/bin/epd2in13b", line 8, in <module>
    sys.exit(main())
  File "/home/pi/workspace/waveshare_imageloader/venv/lib/python3.7/site-packages/epd2in13b/__main__.py", line 41, in main
    frame_black = [0xFF] * (epd.width * epd.height / 8)
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by koenvervloesem** [comment]
Hi @mclucario, as you can see in the issue I referred to, this can be fixed by casting the second operand of the multiplication to an int. There are a lot of these places in the code that need to be fixed, and they are all fixed upstream in https://github.com/soonuse/epd-library-python/pull/12/commits/b2d80ec4a7d193b631028421b5be71c8e2195a42.

**Comment by dhalucario** [comment]
Is there a reason why these haven't been pulled yet?

**Comment by t4skforce** [comment]
Fixed version available on pypi -> https://pypi.org/project/epd-library/0.2.3/
